/* 
  pages/_components/app/AnswerPanel.tsx
  ------------------------
  The answer panel is used by the index page of the webapp
 */

import React, { ReactElement, useEffect } from "react";

interface Props {
  // The QA object controls the answer string and passes it here
  answer: string;
}

export default function AnswerPanel({ answer }: Props): ReactElement {
  return (
    <>
      <div className="p-4 bg-gray-700 rounded-lg shadow-lg ">
        <h1 className="mx-4 mt-2 mb-6 text-xl font-bold">Our Answer</h1>

        {/* Answer to the question generated by AI */}
        <div className="flex flex-wrap ">
          <div className="w-full mx-4 mb-4 ">
            {answer && (
              <p className="text-gray-200 whitespace-pre-wrap">{answer}</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
